# Generated by Django 4.1 on 2022-09-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('numero', models.IntegerField(null=True)),
                ('otro', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=30, null=True)),
                ('direccion', models.ManyToManyField(to='ecopuraApp.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecopuraApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('producto', models.ManyToManyField(to='ecopuraApp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=100)),
                ('p_apellido', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=30, null=True)),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.TextField(max_length=300)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecopuraApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=100)),
                ('p_apellido', models.CharField(max_length=100)),
                ('s_apellido', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecopuraApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_carro', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecopuraApp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.FloatField()),
                ('valor_total', models.IntegerField()),
                ('carrito', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecopuraApp.carrito')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecopuraApp.cliente')),
                ('pago', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecopuraApp.pago')),
            ],
        ),
    ]
