# Generated by Django 4.1 on 2022-09-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0003_remove_carrito_producto_carrito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='kit',
            field=models.ManyToManyField(to='ecopuraApp.kit'),
        ),
    ]
