# Generated by Django 4.0.6 on 2022-11-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0003_alter_mensaje_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='time_of_day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
