# Generated by Django 4.1 on 2022-09-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0004_carrito_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='kit',
            field=models.ManyToManyField(null=True, to='ecopuraApp.kit'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(null=True, to='ecopuraApp.producto'),
        ),
    ]
