# Generated by Django 4.0.6 on 2022-11-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0004_mensaje_time_of_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='time_of_day',
        ),
    ]
