# Generated by Django 4.1 on 2022-09-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0005_alter_carrito_kit_alter_carrito_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='kit',
            field=models.ManyToManyField(blank=True, to='ecopuraApp.kit'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(blank=True, to='ecopuraApp.producto'),
        ),
    ]
