# Generated by Django 4.1 on 2022-09-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0006_alter_carrito_kit_alter_carrito_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='s_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='otro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.ManyToManyField(blank=True, null=True, to='ecopuraApp.direccion'),
        ),
    ]
