# Generated by Django 4.0.6 on 2022-11-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0006_remove_mensaje_usuario_alter_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(to='ecopuraApp.producto'),
        ),
    ]
