# Generated by Django 4.1 on 2022-09-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0007_alter_cliente_s_apellido_alter_contacto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.ManyToManyField(blank=True, to='ecopuraApp.direccion'),
        ),
    ]
