# Generated by Django 4.1 on 2022-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0009_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.ManyToManyField(blank=True, to='ecopuraApp.direccion'),
        ),
    ]
