# Generated by Django 4.1 on 2022-09-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0010_alter_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('producto', models.ManyToManyField(to='ecopuraApp.producto')),
            ],
        ),
    ]
