# Generated by Django 4.1 on 2022-09-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0012_alter_contacto_mensaje_alter_kit_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
