# Generated by Django 4.1.1 on 2022-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0014_tipo_remove_promocion_producto_remove_carrito_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
