# Generated by Django 4.1.1 on 2022-09-28 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0015_alter_tipo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=100)),
                ('p_apellido', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('telefono', models.IntegerField()),
                ('rut_empresa', models.CharField(max_length=12, null=True)),
                ('rut_ver_empresa', models.CharField(max_length=1, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('detalle_dispensador', models.CharField(choices=[('BS', 'Básico'), ('EL', 'Eléctrico'), ('AB', 'Ambos')], default='BS', max_length=2)),
                ('detalle_texto', models.TextField(null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecopuraApp.usuario')),
            ],
        ),
    ]
