# Generated by Django 4.1.1 on 2022-10-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0016_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(null=True, to='ecopuraApp.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.ManyToManyField(blank=True, null=True, to='ecopuraApp.direccion'),
        ),
    ]
