# Generated by Django 4.1.1 on 2022-10-11 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0017_alter_carrito_producto_alter_producto_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='rut_empresa',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='rut_ver_empresa',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecopuraApp.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
