# Generated by Django 4.1.1 on 2022-10-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0018_alter_mensaje_empresa_alter_mensaje_rut_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
