# Generated by Django 4.1.1 on 2022-10-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuraApp', '0019_alter_mensaje_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='rut_empresa',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
