# Generated by Django 4.0.6 on 2022-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
