# Generated by Django 4.0.6 on 2022-11-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_user_name_usuario_nombre_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='is_activate',
        ),
    ]
