# Generated by Django 4.0.6 on 2022-11-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
