# Generated by Django 4.0.6 on 2022-11-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_usuario_nombre_remove_usuario_primer_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='time_of_day',
            field=models.DateTimeField(null=True),
        ),
    ]
