# Generated by Django 4.0.6 on 2022-11-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuario_time_of_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='time_of_day',
        ),
    ]
